### ISSUE TITLE
Using python ABC for abstract classes

### ISSUE THREAD

**Issue by CremaLuca** [ricdezen/sarabanda#1]
I noticed how class `VizSong` is actually an abstract class: 
https://github.com/ricdezen/sarabanda/blob/de78bb3e5af393bc2f810b0e6b83ce74366bc939/src/song.py#L41-L48

Could have used the the `ABC` metaclass and/or `@abstractmethod` decorators.

![Until we meet again](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/f35fb770-7717-41ec-a9d6-0f1d73aba11a/denw5v2-1226b830-3ae0-415c-8f0b-31e1f91e2b9f.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2YzNWZiNzcwLTc3MTctNDFlYy1hOWQ2LTBmMWQ3M2FiYTExYVwvZGVudzV2Mi0xMjI2YjgzMC0zYWUwLTQxNWMtOGYwYi0zMWUxZjkxZTJiOWYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.JuD0DGsnm8ptJ9iEkYSmMbcdagtEj5zFflR8pwNAF-A)

**Comment by ricdezen** [comment]
Lmao
